use_frameworks!

platform :ios, '10.0'

target 'WSMoreButtonControlSwift_Example' do
  pod 'WSMoreButtonControlSwift', :path => '../'

  target 'WSMoreButtonControlSwift_Tests' do
    inherit! :search_paths

    
  end
end
